/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : bigint,
  'matchType' : MatchType,
  'clicks' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'impressions' : bigint,
  'description' : string,
  'bidAmount' : bigint,
  'keywords' : Array<string>,
  'adGroupId' : bigint,
  'destinationUrl' : string,
  'negativeKeywords' : Array<string>,
}
export interface AdMatchResult { 'ad' : Ad, 'keywordScore' : bigint }
export interface AdResult {
  'name' : string,
  'campaignId' : bigint,
  'score' : bigint,
  'bidAmount' : bigint,
  'destinationUrl' : string,
}
export type AdSyncAccountType = { 'business' : null } |
  { 'individual' : null };
export type AdSyncCurrency = { 'EUR' : null } |
  { 'INR' : null } |
  { 'USD' : null };
export interface AdSyncInvoice {
  'id' : bigint,
  'finalAmount' : bigint,
  'createdAt' : bigint,
  'reference' : string,
  'invoiceType' : { 'earning' : null } |
    { 'payout' : null },
  'taxAmount' : bigint,
  'amount' : bigint,
  'syncId' : string,
}
export interface AdSyncKycRecord {
  'status' : AdSyncKycStatus,
  'submittedAt' : [] | [bigint],
  'lastUpdatedAt' : bigint,
  'adminNotes' : string,
  'verifiedAt' : [] | [bigint],
  'syncId' : string,
}
export type AdSyncKycStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'none' : null };
export interface AdSyncPaymentDetails {
  'method' : AdSyncPaymentMethod,
  'country' : string,
  'swiftCode' : [] | [string],
  'iban' : [] | [string],
  'ifsc' : [] | [string],
  'accountName' : string,
  'upiId' : [] | [string],
  'accountNumber' : [] | [string],
  'syncId' : string,
}
export type AdSyncPaymentMethod = { 'upi' : null } |
  { 'bank' : null } |
  { 'swift' : null };
export interface AdSyncPayoutLog {
  'id' : bigint,
  'status' : AdSyncPayoutStatus,
  'completedAt' : [] | [bigint],
  'paymentMethod' : string,
  'createdAt' : bigint,
  'amount' : bigint,
  'syncId' : string,
}
export type AdSyncPayoutStatus = { 'completed' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type AdSyncRole = { 'both' : null } |
  { 'publisher' : null } |
  { 'advertiser' : null };
export interface AdSyncTaxProfile {
  'country' : string,
  'gstNumber' : string,
  'lastUpdatedAt' : bigint,
  'panNumber' : string,
  'taxRate' : bigint,
  'syncId' : string,
}
export interface AdSyncTransaction {
  'id' : bigint,
  'transactionType' : AdSyncTransactionType,
  'createdAt' : bigint,
  'amount' : bigint,
  'syncId' : string,
  'reason' : AdSyncTransactionReason,
}
export type AdSyncTransactionReason = { 'topup' : null } |
  { 'earning' : null } |
  { 'ad_click' : null } |
  { 'payout' : null } |
  { 'refund' : null };
export type AdSyncTransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface AdSyncUser {
  'country' : string,
  'city' : string,
  'createdAt' : bigint,
  'role' : AdSyncRole,
  'fullName' : string,
  'email' : string,
  'kycStatus' : AdSyncKycStatus,
  'state' : string,
  'accountType' : AdSyncAccountType,
  'address' : string,
  'passwordHash' : string,
  'mobile' : string,
  'syncId' : string,
}
export interface AdSyncWallet {
  'balance' : bigint,
  'createdAt' : bigint,
  'totalEarned' : bigint,
  'totalSpent' : bigint,
  'currency' : AdSyncCurrency,
  'syncId' : string,
}
export interface AdvertiserProfile {
  'status' : AdvertiserStatus,
  'appliedAt' : bigint,
  'balance' : bigint,
  'reviewedAt' : [] | [bigint],
  'email' : string,
}
export type AdvertiserStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AdvertiserWallet {
  'balance' : bigint,
  'createdAt' : bigint,
  'email' : string,
  'totalSpent' : bigint,
}
export interface BlacklistEntry {
  'status' : BlacklistStatus,
  'domain' : string,
  'reviewedBy' : [] | [string],
  'addedAt' : bigint,
  'reason' : string,
}
export type BlacklistStatus = { 'blocked' : null } |
  { 'flagged' : null };
export interface Campaign {
  'id' : bigint,
  'status' : CampaignStatus,
  'clicks' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'advertiserEmail' : string,
  'impressions' : bigint,
  'bidAmount' : bigint,
  'keywords' : Array<string>,
  'spend' : bigint,
  'dailyBudget' : bigint,
  'destinationUrl' : string,
  'budget' : bigint,
}
export type CampaignStatus = { 'active' : null } |
  { 'ended' : null } |
  { 'paused' : null };
export interface DiscoverFeed {
  'popularDomains' : Array<Website>,
  'recentlyIndexed' : Array<Website>,
  'trending' : Array<Website>,
  'recommendedForYou' : Array<Website>,
}
export type IndexStatus = { 'pending' : null } |
  { 'error' : null } |
  { 'notIndexed' : null } |
  { 'indexed' : null };
export type MatchType = { 'exact' : null } |
  { 'broad' : null } |
  { 'phrase' : null };
export type OwnershipStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'reclaimed' : null };
export interface Page {
  'id' : bigint,
  'url' : string,
  'status' : PageStatus,
  'websiteId' : bigint,
  'addedAt' : bigint,
}
export type PageStatus = { 'pending' : null } |
  { 'error' : null } |
  { 'indexed' : null };
export type Result = { 'ok' : AdvertiserWallet } |
  { 'err' : string };
export type Result_1 = { 'ok' : AdSyncWallet } |
  { 'err' : string };
export type Result_2 = { 'ok' : AdSyncKycRecord } |
  { 'err' : string };
export type Result_3 = { 'ok' : string } |
  { 'err' : string };
export type Result_4 = { 'ok' : AdSyncPaymentDetails } |
  { 'err' : string };
export type Result_5 = { 'ok' : AdSyncUser } |
  { 'err' : string };
export type Result_6 = { 'ok' : null } |
  { 'err' : string };
export type Result_7 = { 'ok' : AdSyncTaxProfile } |
  { 'err' : string };
export type Result_8 = {
    'ok' : { 'orderId' : string, 'amount' : bigint, 'keyId' : string }
  } |
  { 'err' : string };
export interface SecurityLog {
  'id' : bigint,
  'logType' : string,
  'timestamp' : bigint,
  'details' : string,
  'principalText' : string,
}
export interface SeedEntry {
  'url' : string,
  'title' : string,
  'description' : string,
  'keywords' : Array<string>,
}
export interface Stats {
  'total' : bigint,
  'pending' : bigint,
  'approved' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'createdAt' : bigint,
  'type' : TransactionType,
  'email' : string,
  'amount' : bigint,
  'reason' : TransactionReason,
}
export type TransactionReason = { 'topup' : null } |
  { 'ad_click' : null } |
  { 'refund' : null };
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'verified' : null } |
  { 'expired' : null } |
  { 'pending' : null };
export interface Website {
  'id' : bigint,
  'url' : string,
  'status' : WebsiteStatus,
  'clicks' : bigint,
  'title' : string,
  'indexStatus' : IndexStatus,
  'spamScore' : bigint,
  'ownerId' : string,
  'ownerPrincipal' : [] | [Principal],
  'approvedAt' : [] | [bigint],
  'verificationToken' : string,
  'lastVerifiedAt' : [] | [bigint],
  'ownershipStatus' : OwnershipStatus,
  'impressions' : bigint,
  'submittedAt' : bigint,
  'description' : string,
  'verificationExpiryAt' : [] | [bigint],
  'isSeed' : boolean,
  'keywords' : Array<string>,
  'seoScore' : bigint,
  'isVerified' : boolean,
  'lastCheckedAt' : [] | [bigint],
  'lastCrawledAt' : [] | [bigint],
  'ownerHistory' : Array<string>,
  'verificationStatus' : VerificationStatus,
  'adminBoost' : bigint,
  'sitemapUrl' : [] | [string],
}
export type WebsiteStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAdSyncBalance' : ActorMethod<[string, bigint], Result_1>,
  'addAdvertiserBalance' : ActorMethod<[string, bigint], undefined>,
  'addBalance' : ActorMethod<[string, bigint], Result>,
  'addToBlacklist' : ActorMethod<[string, string], undefined>,
  'addToCrawlQueue' : ActorMethod<[bigint], undefined>,
  'adminUpdateAdSyncKycStatus' : ActorMethod<
    [string, AdSyncKycStatus, string],
    Result_2
  >,
  'adminUpdatePayoutStatus' : ActorMethod<
    [bigint, AdSyncPayoutStatus],
    Result_3
  >,
  'applyForAdvertiser' : ActorMethod<[string], undefined>,
  'approveAdvertiser' : ActorMethod<[string], undefined>,
  'approveWebsite' : ActorMethod<[bigint], Website>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndQueueRecrawl' : ActorMethod<[], bigint>,
  'createAdSyncRazorpayOrder' : ActorMethod<[string, bigint], Result_8>,
  'createCampaign' : ActorMethod<
    [string, string, bigint, bigint, bigint, Array<string>, string],
    Campaign
  >,
  'createRazorpayOrder' : ActorMethod<[string, bigint], Result_8>,
  'createWallet' : ActorMethod<[string], AdvertiserWallet>,
  'deductOnAdClick' : ActorMethod<[string, string, bigint, string], Result_3>,
  'deleteWebsite' : ActorMethod<[bigint], undefined>,
  'editWebsite' : ActorMethod<[bigint, string, string, Array<string>], Website>,
  'getAdSyncInvoices' : ActorMethod<[string], Array<AdSyncInvoice>>,
  'getAdSyncKycRecord' : ActorMethod<[string], [] | [AdSyncKycRecord]>,
  'getAdSyncPaymentDetails' : ActorMethod<
    [string],
    [] | [AdSyncPaymentDetails]
  >,
  'getAdSyncPayoutLogs' : ActorMethod<[string], Array<AdSyncPayoutLog>>,
  'getAdSyncRevenueShare' : ActorMethod<[], bigint>,
  'getAdSyncTaxProfile' : ActorMethod<[string], Result_7>,
  'getAdSyncTransactions' : ActorMethod<[string], Array<AdSyncTransaction>>,
  'getAdSyncUser' : ActorMethod<[string], [] | [AdSyncUser]>,
  'getAdSyncUserBySyncId' : ActorMethod<[string], [] | [AdSyncUser]>,
  'getAdSyncWallet' : ActorMethod<[string], [] | [AdSyncWallet]>,
  'getAdsEnabled' : ActorMethod<[], boolean>,
  'getAdsForSearch' : ActorMethod<[string], Array<AdResult>>,
  'getAllAdvertiserApplications' : ActorMethod<[], Array<AdvertiserProfile>>,
  'getAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllWebsites' : ActorMethod<[], Array<Website>>,
  'getBlacklist' : ActorMethod<[], Array<BlacklistEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrawlQueue' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getDiscoverFeed' : ActorMethod<[[] | [string]], DiscoverFeed>,
  'getFlaggedDomains' : ActorMethod<[], Array<BlacklistEntry>>,
  'getMyAdvertiserProfile' : ActorMethod<[string], [] | [AdvertiserProfile]>,
  'getMyCampaigns' : ActorMethod<[string], Array<Campaign>>,
  'getMyWebsites' : ActorMethod<[], Array<Website>>,
  'getMyWebsitesByEmail' : ActorMethod<[string], Array<Website>>,
  'getPagesForWebsite' : ActorMethod<[bigint], Array<Page>>,
  'getPendingWebsites' : ActorMethod<[], Array<Website>>,
  'getSecurityLogs' : ActorMethod<[], Array<SecurityLog>>,
  'getStats' : ActorMethod<[], Stats>,
  'getTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getUserClickHistory' : ActorMethod<[string], Array<string>>,
  'getUserInterests' : ActorMethod<[string], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSearchHistory' : ActorMethod<[string], Array<string>>,
  'getVerificationToken' : ActorMethod<[bigint], string>,
  'getWallet' : ActorMethod<[string], [] | [AdvertiserWallet]>,
  'importSeedData' : ActorMethod<[Array<SeedEntry>], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginAdSyncUser' : ActorMethod<[string, string], Result_5>,
  'pauseCampaign' : ActorMethod<[bigint], undefined>,
  'processPayouts' : ActorMethod<[], Array<AdSyncPayoutLog>>,
  'rankAds' : ActorMethod<[string], Array<AdMatchResult>>,
  'recalculateAllSpamScores' : ActorMethod<[], bigint>,
  'recalculateSpamScore' : ActorMethod<[bigint], bigint>,
  'reclaimDomain' : ActorMethod<[bigint, string], Website>,
  'recordAdClick' : ActorMethod<[bigint, string], Result_6>,
  'recordAdClickV2' : ActorMethod<[bigint, string], Result_6>,
  'recordAdImpression' : ActorMethod<[bigint], undefined>,
  'recordAdImpressionV2' : ActorMethod<[bigint], undefined>,
  'recordClick' : ActorMethod<[string], undefined>,
  'recordImpression' : ActorMethod<[string], undefined>,
  'recordUserClick' : ActorMethod<[string, string], undefined>,
  'recordUserSearch' : ActorMethod<[string, string], undefined>,
  'refreshUserInterests' : ActorMethod<[string], undefined>,
  'registerAdSyncUser' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      AdSyncAccountType,
      AdSyncRole,
      string,
      string,
      string,
      string,
    ],
    Result_5
  >,
  'rejectAdvertiser' : ActorMethod<[string], undefined>,
  'rejectWebsite' : ActorMethod<[bigint], Website>,
  'removeFromBlacklist' : ActorMethod<[string], undefined>,
  'requestIndexing' : ActorMethod<[bigint, string], Website>,
  'resumeCampaign' : ActorMethod<[bigint], undefined>,
  'reviewFlaggedDomain' : ActorMethod<
    [string, { 'remove' : null } | { 'approve' : null } | { 'block' : null }],
    undefined
  >,
  'runCrawler' : ActorMethod<[], bigint>,
  'runOwnershipCleanup' : ActorMethod<[], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchWebsites' : ActorMethod<[string, [] | [string]], Array<Website>>,
  'setAdSyncPaymentDetails' : ActorMethod<
    [
      string,
      string,
      AdSyncPaymentMethod,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      string,
    ],
    Result_4
  >,
  'setAdSyncRevenueShare' : ActorMethod<[bigint], Result_3>,
  'setAdSyncTaxProfile' : ActorMethod<
    [string, string, string, string, bigint],
    Result_3
  >,
  'setAdminBoost' : ActorMethod<[bigint, bigint], Website>,
  'setAdsEnabled' : ActorMethod<[boolean], undefined>,
  'submitAdSyncKyc' : ActorMethod<[string], Result_2>,
  'submitWebsite' : ActorMethod<
    [string, string, string, string, Array<string>],
    Website
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCampaign' : ActorMethod<
    [bigint, string, bigint, bigint, bigint, Array<string>, string],
    Campaign
  >,
  'updateLastCrawledAt' : ActorMethod<[bigint], undefined>,
  'updatePageStatus' : ActorMethod<[bigint, PageStatus], undefined>,
  'updateSitemap' : ActorMethod<[bigint, string], Website>,
  'verifyAdSyncRazorpayPayment' : ActorMethod<
    [string, string, string, string, bigint],
    Result_1
  >,
  'verifyDomain' : ActorMethod<[bigint], boolean>,
  'verifyRazorpayPayment' : ActorMethod<
    [string, string, string, string, bigint],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];