/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdSyncCurrency = IDL.Variant({
  'EUR' : IDL.Null,
  'INR' : IDL.Null,
  'USD' : IDL.Null,
});
export const AdSyncWallet = IDL.Record({
  'balance' : IDL.Nat,
  'createdAt' : IDL.Int,
  'totalEarned' : IDL.Nat,
  'totalSpent' : IDL.Nat,
  'currency' : AdSyncCurrency,
  'syncId' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : AdSyncWallet, 'err' : IDL.Text });
export const AdvertiserWallet = IDL.Record({
  'balance' : IDL.Nat,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'totalSpent' : IDL.Nat,
});
export const Result = IDL.Variant({
  'ok' : AdvertiserWallet,
  'err' : IDL.Text,
});
export const AdSyncKycStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'none' : IDL.Null,
});
export const AdSyncKycRecord = IDL.Record({
  'status' : AdSyncKycStatus,
  'submittedAt' : IDL.Opt(IDL.Int),
  'lastUpdatedAt' : IDL.Int,
  'adminNotes' : IDL.Text,
  'verifiedAt' : IDL.Opt(IDL.Int),
  'syncId' : IDL.Text,
});
export const Result_2 = IDL.Variant({
  'ok' : AdSyncKycRecord,
  'err' : IDL.Text,
});
export const AdSyncPayoutStatus = IDL.Variant({
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const WebsiteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const IndexStatus = IDL.Variant({
  'pending' : IDL.Null,
  'error' : IDL.Null,
  'notIndexed' : IDL.Null,
  'indexed' : IDL.Null,
});
export const OwnershipStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'reclaimed' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
});
export const Website = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'status' : WebsiteStatus,
  'clicks' : IDL.Nat,
  'title' : IDL.Text,
  'indexStatus' : IndexStatus,
  'spamScore' : IDL.Nat,
  'ownerId' : IDL.Text,
  'ownerPrincipal' : IDL.Opt(IDL.Principal),
  'approvedAt' : IDL.Opt(IDL.Int),
  'verificationToken' : IDL.Text,
  'lastVerifiedAt' : IDL.Opt(IDL.Int),
  'ownershipStatus' : OwnershipStatus,
  'impressions' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'verificationExpiryAt' : IDL.Opt(IDL.Int),
  'isSeed' : IDL.Bool,
  'keywords' : IDL.Vec(IDL.Text),
  'seoScore' : IDL.Nat,
  'isVerified' : IDL.Bool,
  'lastCheckedAt' : IDL.Opt(IDL.Int),
  'lastCrawledAt' : IDL.Opt(IDL.Int),
  'ownerHistory' : IDL.Vec(IDL.Text),
  'verificationStatus' : VerificationStatus,
  'adminBoost' : IDL.Nat,
  'sitemapUrl' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Record({
    'orderId' : IDL.Text,
    'amount' : IDL.Nat,
    'keyId' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const CampaignStatus = IDL.Variant({
  'active' : IDL.Null,
  'ended' : IDL.Null,
  'paused' : IDL.Null,
});
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'status' : CampaignStatus,
  'clicks' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'advertiserEmail' : IDL.Text,
  'impressions' : IDL.Nat,
  'bidAmount' : IDL.Nat,
  'keywords' : IDL.Vec(IDL.Text),
  'spend' : IDL.Nat,
  'dailyBudget' : IDL.Nat,
  'destinationUrl' : IDL.Text,
  'budget' : IDL.Nat,
});
export const AdSyncInvoice = IDL.Record({
  'id' : IDL.Nat,
  'finalAmount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'reference' : IDL.Text,
  'invoiceType' : IDL.Variant({ 'earning' : IDL.Null, 'payout' : IDL.Null }),
  'taxAmount' : IDL.Nat,
  'amount' : IDL.Nat,
  'syncId' : IDL.Text,
});
export const AdSyncPaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'bank' : IDL.Null,
  'swift' : IDL.Null,
});
export const AdSyncPaymentDetails = IDL.Record({
  'method' : AdSyncPaymentMethod,
  'country' : IDL.Text,
  'swiftCode' : IDL.Opt(IDL.Text),
  'iban' : IDL.Opt(IDL.Text),
  'ifsc' : IDL.Opt(IDL.Text),
  'accountName' : IDL.Text,
  'upiId' : IDL.Opt(IDL.Text),
  'accountNumber' : IDL.Opt(IDL.Text),
  'syncId' : IDL.Text,
});
export const AdSyncPayoutLog = IDL.Record({
  'id' : IDL.Nat,
  'status' : AdSyncPayoutStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'amount' : IDL.Nat,
  'syncId' : IDL.Text,
});
export const AdSyncTaxProfile = IDL.Record({
  'country' : IDL.Text,
  'gstNumber' : IDL.Text,
  'lastUpdatedAt' : IDL.Int,
  'panNumber' : IDL.Text,
  'taxRate' : IDL.Nat,
  'syncId' : IDL.Text,
});
export const Result_7 = IDL.Variant({
  'ok' : AdSyncTaxProfile,
  'err' : IDL.Text,
});
export const AdSyncTransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const AdSyncTransactionReason = IDL.Variant({
  'topup' : IDL.Null,
  'earning' : IDL.Null,
  'ad_click' : IDL.Null,
  'payout' : IDL.Null,
  'refund' : IDL.Null,
});
export const AdSyncTransaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : AdSyncTransactionType,
  'createdAt' : IDL.Int,
  'amount' : IDL.Nat,
  'syncId' : IDL.Text,
  'reason' : AdSyncTransactionReason,
});
export const AdSyncRole = IDL.Variant({
  'both' : IDL.Null,
  'publisher' : IDL.Null,
  'advertiser' : IDL.Null,
});
export const AdSyncAccountType = IDL.Variant({
  'business' : IDL.Null,
  'individual' : IDL.Null,
});
export const AdSyncUser = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : AdSyncRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'kycStatus' : AdSyncKycStatus,
  'state' : IDL.Text,
  'accountType' : AdSyncAccountType,
  'address' : IDL.Text,
  'passwordHash' : IDL.Text,
  'mobile' : IDL.Text,
  'syncId' : IDL.Text,
});
export const AdResult = IDL.Record({
  'name' : IDL.Text,
  'campaignId' : IDL.Nat,
  'score' : IDL.Nat,
  'bidAmount' : IDL.Nat,
  'destinationUrl' : IDL.Text,
});
export const AdvertiserStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AdvertiserProfile = IDL.Record({
  'status' : AdvertiserStatus,
  'appliedAt' : IDL.Int,
  'balance' : IDL.Nat,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
});
export const BlacklistStatus = IDL.Variant({
  'blocked' : IDL.Null,
  'flagged' : IDL.Null,
});
export const BlacklistEntry = IDL.Record({
  'status' : BlacklistStatus,
  'domain' : IDL.Text,
  'reviewedBy' : IDL.Opt(IDL.Text),
  'addedAt' : IDL.Int,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'email' : IDL.Text });
export const DiscoverFeed = IDL.Record({
  'popularDomains' : IDL.Vec(Website),
  'recentlyIndexed' : IDL.Vec(Website),
  'trending' : IDL.Vec(Website),
  'recommendedForYou' : IDL.Vec(Website),
});
export const PageStatus = IDL.Variant({
  'pending' : IDL.Null,
  'error' : IDL.Null,
  'indexed' : IDL.Null,
});
export const Page = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'status' : PageStatus,
  'websiteId' : IDL.Nat,
  'addedAt' : IDL.Int,
});
export const SecurityLog = IDL.Record({
  'id' : IDL.Nat,
  'logType' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'principalText' : IDL.Text,
});
export const Stats = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'approved' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const TransactionReason = IDL.Variant({
  'topup' : IDL.Null,
  'ad_click' : IDL.Null,
  'refund' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'type' : TransactionType,
  'email' : IDL.Text,
  'amount' : IDL.Nat,
  'reason' : TransactionReason,
});
export const SeedEntry = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
});
export const Result_5 = IDL.Variant({ 'ok' : AdSyncUser, 'err' : IDL.Text });
export const MatchType = IDL.Variant({
  'exact' : IDL.Null,
  'broad' : IDL.Null,
  'phrase' : IDL.Null,
});
export const Ad = IDL.Record({
  'id' : IDL.Nat,
  'matchType' : MatchType,
  'clicks' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'impressions' : IDL.Nat,
  'description' : IDL.Text,
  'bidAmount' : IDL.Nat,
  'keywords' : IDL.Vec(IDL.Text),
  'adGroupId' : IDL.Nat,
  'destinationUrl' : IDL.Text,
  'negativeKeywords' : IDL.Vec(IDL.Text),
});
export const AdMatchResult = IDL.Record({
  'ad' : Ad,
  'keywordScore' : IDL.Nat,
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({
  'ok' : AdSyncPaymentDetails,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAdSyncBalance' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
  'addAdvertiserBalance' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addBalance' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
  'addToBlacklist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addToCrawlQueue' : IDL.Func([IDL.Nat], [], []),
  'adminUpdateAdSyncKycStatus' : IDL.Func(
      [IDL.Text, AdSyncKycStatus, IDL.Text],
      [Result_2],
      [],
    ),
  'adminUpdatePayoutStatus' : IDL.Func(
      [IDL.Nat, AdSyncPayoutStatus],
      [Result_3],
      [],
    ),
  'applyForAdvertiser' : IDL.Func([IDL.Text], [], []),
  'approveAdvertiser' : IDL.Func([IDL.Text], [], []),
  'approveWebsite' : IDL.Func([IDL.Nat], [Website], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndQueueRecrawl' : IDL.Func([], [IDL.Nat], []),
  'createAdSyncRazorpayOrder' : IDL.Func([IDL.Text, IDL.Nat], [Result_8], []),
  'createCampaign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [Campaign],
      [],
    ),
  'createRazorpayOrder' : IDL.Func([IDL.Text, IDL.Nat], [Result_8], []),
  'createWallet' : IDL.Func([IDL.Text], [AdvertiserWallet], []),
  'deductOnAdClick' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Result_3],
      [],
    ),
  'deleteWebsite' : IDL.Func([IDL.Nat], [], []),
  'editWebsite' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Website],
      [],
    ),
  'getAdSyncInvoices' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdSyncInvoice)],
      ['query'],
    ),
  'getAdSyncKycRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdSyncKycRecord)],
      ['query'],
    ),
  'getAdSyncPaymentDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdSyncPaymentDetails)],
      ['query'],
    ),
  'getAdSyncPayoutLogs' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdSyncPayoutLog)],
      ['query'],
    ),
  'getAdSyncRevenueShare' : IDL.Func([], [IDL.Nat], ['query']),
  'getAdSyncTaxProfile' : IDL.Func([IDL.Text], [Result_7], ['query']),
  'getAdSyncTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdSyncTransaction)],
      ['query'],
    ),
  'getAdSyncUser' : IDL.Func([IDL.Text], [IDL.Opt(AdSyncUser)], ['query']),
  'getAdSyncUserBySyncId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdSyncUser)],
      ['query'],
    ),
  'getAdSyncWallet' : IDL.Func([IDL.Text], [IDL.Opt(AdSyncWallet)], ['query']),
  'getAdsEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getAdsForSearch' : IDL.Func([IDL.Text], [IDL.Vec(AdResult)], []),
  'getAllAdvertiserApplications' : IDL.Func(
      [],
      [IDL.Vec(AdvertiserProfile)],
      ['query'],
    ),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
  'getBlacklist' : IDL.Func([], [IDL.Vec(BlacklistEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrawlQueue' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getDiscoverFeed' : IDL.Func([IDL.Opt(IDL.Text)], [DiscoverFeed], ['query']),
  'getFlaggedDomains' : IDL.Func([], [IDL.Vec(BlacklistEntry)], ['query']),
  'getMyAdvertiserProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdvertiserProfile)],
      ['query'],
    ),
  'getMyCampaigns' : IDL.Func([IDL.Text], [IDL.Vec(Campaign)], []),
  'getMyWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
  'getMyWebsitesByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Website)], ['query']),
  'getPagesForWebsite' : IDL.Func([IDL.Nat], [IDL.Vec(Page)], ['query']),
  'getPendingWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
  'getSecurityLogs' : IDL.Func([], [IDL.Vec(SecurityLog)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
  'getUserClickHistory' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserInterests' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSearchHistory' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getVerificationToken' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getWallet' : IDL.Func([IDL.Text], [IDL.Opt(AdvertiserWallet)], ['query']),
  'importSeedData' : IDL.Func([IDL.Vec(SeedEntry)], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAdSyncUser' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'pauseCampaign' : IDL.Func([IDL.Nat], [], []),
  'processPayouts' : IDL.Func([], [IDL.Vec(AdSyncPayoutLog)], []),
  'rankAds' : IDL.Func([IDL.Text], [IDL.Vec(AdMatchResult)], ['query']),
  'recalculateAllSpamScores' : IDL.Func([], [IDL.Nat], []),
  'recalculateSpamScore' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'reclaimDomain' : IDL.Func([IDL.Nat, IDL.Text], [Website], []),
  'recordAdClick' : IDL.Func([IDL.Nat, IDL.Text], [Result_6], []),
  'recordAdClickV2' : IDL.Func([IDL.Nat, IDL.Text], [Result_6], []),
  'recordAdImpression' : IDL.Func([IDL.Nat], [], []),
  'recordAdImpressionV2' : IDL.Func([IDL.Nat], [], []),
  'recordClick' : IDL.Func([IDL.Text], [], []),
  'recordImpression' : IDL.Func([IDL.Text], [], []),
  'recordUserClick' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordUserSearch' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'refreshUserInterests' : IDL.Func([IDL.Text], [], []),
  'registerAdSyncUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AdSyncAccountType,
        AdSyncRole,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Result_5],
      [],
    ),
  'rejectAdvertiser' : IDL.Func([IDL.Text], [], []),
  'rejectWebsite' : IDL.Func([IDL.Nat], [Website], []),
  'removeFromBlacklist' : IDL.Func([IDL.Text], [], []),
  'requestIndexing' : IDL.Func([IDL.Nat, IDL.Text], [Website], []),
  'resumeCampaign' : IDL.Func([IDL.Nat], [], []),
  'reviewFlaggedDomain' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'remove' : IDL.Null,
          'approve' : IDL.Null,
          'block' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'runCrawler' : IDL.Func([], [IDL.Nat], []),
  'runOwnershipCleanup' : IDL.Func([], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchWebsites' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(Website)],
      ['query'],
    ),
  'setAdSyncPaymentDetails' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        AdSyncPaymentMethod,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [Result_4],
      [],
    ),
  'setAdSyncRevenueShare' : IDL.Func([IDL.Nat], [Result_3], []),
  'setAdSyncTaxProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_3],
      [],
    ),
  'setAdminBoost' : IDL.Func([IDL.Nat, IDL.Nat], [Website], []),
  'setAdsEnabled' : IDL.Func([IDL.Bool], [], []),
  'submitAdSyncKyc' : IDL.Func([IDL.Text], [Result_2], []),
  'submitWebsite' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Website],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCampaign' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [Campaign],
      [],
    ),
  'updateLastCrawledAt' : IDL.Func([IDL.Nat], [], []),
  'updatePageStatus' : IDL.Func([IDL.Nat, PageStatus], [], []),
  'updateSitemap' : IDL.Func([IDL.Nat, IDL.Text], [Website], []),
  'verifyAdSyncRazorpayPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_1],
      [],
    ),
  'verifyDomain' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'verifyRazorpayPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdSyncCurrency = IDL.Variant({
    'EUR' : IDL.Null,
    'INR' : IDL.Null,
    'USD' : IDL.Null,
  });
  const AdSyncWallet = IDL.Record({
    'balance' : IDL.Nat,
    'createdAt' : IDL.Int,
    'totalEarned' : IDL.Nat,
    'totalSpent' : IDL.Nat,
    'currency' : AdSyncCurrency,
    'syncId' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : AdSyncWallet, 'err' : IDL.Text });
  const AdvertiserWallet = IDL.Record({
    'balance' : IDL.Nat,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'totalSpent' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : AdvertiserWallet, 'err' : IDL.Text });
  const AdSyncKycStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'none' : IDL.Null,
  });
  const AdSyncKycRecord = IDL.Record({
    'status' : AdSyncKycStatus,
    'submittedAt' : IDL.Opt(IDL.Int),
    'lastUpdatedAt' : IDL.Int,
    'adminNotes' : IDL.Text,
    'verifiedAt' : IDL.Opt(IDL.Int),
    'syncId' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : AdSyncKycRecord, 'err' : IDL.Text });
  const AdSyncPayoutStatus = IDL.Variant({
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const WebsiteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const IndexStatus = IDL.Variant({
    'pending' : IDL.Null,
    'error' : IDL.Null,
    'notIndexed' : IDL.Null,
    'indexed' : IDL.Null,
  });
  const OwnershipStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'reclaimed' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Website = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'status' : WebsiteStatus,
    'clicks' : IDL.Nat,
    'title' : IDL.Text,
    'indexStatus' : IndexStatus,
    'spamScore' : IDL.Nat,
    'ownerId' : IDL.Text,
    'ownerPrincipal' : IDL.Opt(IDL.Principal),
    'approvedAt' : IDL.Opt(IDL.Int),
    'verificationToken' : IDL.Text,
    'lastVerifiedAt' : IDL.Opt(IDL.Int),
    'ownershipStatus' : OwnershipStatus,
    'impressions' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'verificationExpiryAt' : IDL.Opt(IDL.Int),
    'isSeed' : IDL.Bool,
    'keywords' : IDL.Vec(IDL.Text),
    'seoScore' : IDL.Nat,
    'isVerified' : IDL.Bool,
    'lastCheckedAt' : IDL.Opt(IDL.Int),
    'lastCrawledAt' : IDL.Opt(IDL.Int),
    'ownerHistory' : IDL.Vec(IDL.Text),
    'verificationStatus' : VerificationStatus,
    'adminBoost' : IDL.Nat,
    'sitemapUrl' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Record({
      'orderId' : IDL.Text,
      'amount' : IDL.Nat,
      'keyId' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const CampaignStatus = IDL.Variant({
    'active' : IDL.Null,
    'ended' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'status' : CampaignStatus,
    'clicks' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'advertiserEmail' : IDL.Text,
    'impressions' : IDL.Nat,
    'bidAmount' : IDL.Nat,
    'keywords' : IDL.Vec(IDL.Text),
    'spend' : IDL.Nat,
    'dailyBudget' : IDL.Nat,
    'destinationUrl' : IDL.Text,
    'budget' : IDL.Nat,
  });
  const AdSyncInvoice = IDL.Record({
    'id' : IDL.Nat,
    'finalAmount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'reference' : IDL.Text,
    'invoiceType' : IDL.Variant({ 'earning' : IDL.Null, 'payout' : IDL.Null }),
    'taxAmount' : IDL.Nat,
    'amount' : IDL.Nat,
    'syncId' : IDL.Text,
  });
  const AdSyncPaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'bank' : IDL.Null,
    'swift' : IDL.Null,
  });
  const AdSyncPaymentDetails = IDL.Record({
    'method' : AdSyncPaymentMethod,
    'country' : IDL.Text,
    'swiftCode' : IDL.Opt(IDL.Text),
    'iban' : IDL.Opt(IDL.Text),
    'ifsc' : IDL.Opt(IDL.Text),
    'accountName' : IDL.Text,
    'upiId' : IDL.Opt(IDL.Text),
    'accountNumber' : IDL.Opt(IDL.Text),
    'syncId' : IDL.Text,
  });
  const AdSyncPayoutLog = IDL.Record({
    'id' : IDL.Nat,
    'status' : AdSyncPayoutStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
    'syncId' : IDL.Text,
  });
  const AdSyncTaxProfile = IDL.Record({
    'country' : IDL.Text,
    'gstNumber' : IDL.Text,
    'lastUpdatedAt' : IDL.Int,
    'panNumber' : IDL.Text,
    'taxRate' : IDL.Nat,
    'syncId' : IDL.Text,
  });
  const Result_7 = IDL.Variant({ 'ok' : AdSyncTaxProfile, 'err' : IDL.Text });
  const AdSyncTransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const AdSyncTransactionReason = IDL.Variant({
    'topup' : IDL.Null,
    'earning' : IDL.Null,
    'ad_click' : IDL.Null,
    'payout' : IDL.Null,
    'refund' : IDL.Null,
  });
  const AdSyncTransaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : AdSyncTransactionType,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
    'syncId' : IDL.Text,
    'reason' : AdSyncTransactionReason,
  });
  const AdSyncRole = IDL.Variant({
    'both' : IDL.Null,
    'publisher' : IDL.Null,
    'advertiser' : IDL.Null,
  });
  const AdSyncAccountType = IDL.Variant({
    'business' : IDL.Null,
    'individual' : IDL.Null,
  });
  const AdSyncUser = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : AdSyncRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'kycStatus' : AdSyncKycStatus,
    'state' : IDL.Text,
    'accountType' : AdSyncAccountType,
    'address' : IDL.Text,
    'passwordHash' : IDL.Text,
    'mobile' : IDL.Text,
    'syncId' : IDL.Text,
  });
  const AdResult = IDL.Record({
    'name' : IDL.Text,
    'campaignId' : IDL.Nat,
    'score' : IDL.Nat,
    'bidAmount' : IDL.Nat,
    'destinationUrl' : IDL.Text,
  });
  const AdvertiserStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AdvertiserProfile = IDL.Record({
    'status' : AdvertiserStatus,
    'appliedAt' : IDL.Int,
    'balance' : IDL.Nat,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
  });
  const BlacklistStatus = IDL.Variant({
    'blocked' : IDL.Null,
    'flagged' : IDL.Null,
  });
  const BlacklistEntry = IDL.Record({
    'status' : BlacklistStatus,
    'domain' : IDL.Text,
    'reviewedBy' : IDL.Opt(IDL.Text),
    'addedAt' : IDL.Int,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'email' : IDL.Text });
  const DiscoverFeed = IDL.Record({
    'popularDomains' : IDL.Vec(Website),
    'recentlyIndexed' : IDL.Vec(Website),
    'trending' : IDL.Vec(Website),
    'recommendedForYou' : IDL.Vec(Website),
  });
  const PageStatus = IDL.Variant({
    'pending' : IDL.Null,
    'error' : IDL.Null,
    'indexed' : IDL.Null,
  });
  const Page = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'status' : PageStatus,
    'websiteId' : IDL.Nat,
    'addedAt' : IDL.Int,
  });
  const SecurityLog = IDL.Record({
    'id' : IDL.Nat,
    'logType' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'principalText' : IDL.Text,
  });
  const Stats = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'approved' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const TransactionReason = IDL.Variant({
    'topup' : IDL.Null,
    'ad_click' : IDL.Null,
    'refund' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'type' : TransactionType,
    'email' : IDL.Text,
    'amount' : IDL.Nat,
    'reason' : TransactionReason,
  });
  const SeedEntry = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
  });
  const Result_5 = IDL.Variant({ 'ok' : AdSyncUser, 'err' : IDL.Text });
  const MatchType = IDL.Variant({
    'exact' : IDL.Null,
    'broad' : IDL.Null,
    'phrase' : IDL.Null,
  });
  const Ad = IDL.Record({
    'id' : IDL.Nat,
    'matchType' : MatchType,
    'clicks' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'impressions' : IDL.Nat,
    'description' : IDL.Text,
    'bidAmount' : IDL.Nat,
    'keywords' : IDL.Vec(IDL.Text),
    'adGroupId' : IDL.Nat,
    'destinationUrl' : IDL.Text,
    'negativeKeywords' : IDL.Vec(IDL.Text),
  });
  const AdMatchResult = IDL.Record({ 'ad' : Ad, 'keywordScore' : IDL.Nat });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({
    'ok' : AdSyncPaymentDetails,
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAdSyncBalance' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
    'addAdvertiserBalance' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addBalance' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
    'addToBlacklist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addToCrawlQueue' : IDL.Func([IDL.Nat], [], []),
    'adminUpdateAdSyncKycStatus' : IDL.Func(
        [IDL.Text, AdSyncKycStatus, IDL.Text],
        [Result_2],
        [],
      ),
    'adminUpdatePayoutStatus' : IDL.Func(
        [IDL.Nat, AdSyncPayoutStatus],
        [Result_3],
        [],
      ),
    'applyForAdvertiser' : IDL.Func([IDL.Text], [], []),
    'approveAdvertiser' : IDL.Func([IDL.Text], [], []),
    'approveWebsite' : IDL.Func([IDL.Nat], [Website], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndQueueRecrawl' : IDL.Func([], [IDL.Nat], []),
    'createAdSyncRazorpayOrder' : IDL.Func([IDL.Text, IDL.Nat], [Result_8], []),
    'createCampaign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [Campaign],
        [],
      ),
    'createRazorpayOrder' : IDL.Func([IDL.Text, IDL.Nat], [Result_8], []),
    'createWallet' : IDL.Func([IDL.Text], [AdvertiserWallet], []),
    'deductOnAdClick' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Result_3],
        [],
      ),
    'deleteWebsite' : IDL.Func([IDL.Nat], [], []),
    'editWebsite' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Website],
        [],
      ),
    'getAdSyncInvoices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdSyncInvoice)],
        ['query'],
      ),
    'getAdSyncKycRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdSyncKycRecord)],
        ['query'],
      ),
    'getAdSyncPaymentDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdSyncPaymentDetails)],
        ['query'],
      ),
    'getAdSyncPayoutLogs' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdSyncPayoutLog)],
        ['query'],
      ),
    'getAdSyncRevenueShare' : IDL.Func([], [IDL.Nat], ['query']),
    'getAdSyncTaxProfile' : IDL.Func([IDL.Text], [Result_7], ['query']),
    'getAdSyncTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdSyncTransaction)],
        ['query'],
      ),
    'getAdSyncUser' : IDL.Func([IDL.Text], [IDL.Opt(AdSyncUser)], ['query']),
    'getAdSyncUserBySyncId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdSyncUser)],
        ['query'],
      ),
    'getAdSyncWallet' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdSyncWallet)],
        ['query'],
      ),
    'getAdsEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getAdsForSearch' : IDL.Func([IDL.Text], [IDL.Vec(AdResult)], []),
    'getAllAdvertiserApplications' : IDL.Func(
        [],
        [IDL.Vec(AdvertiserProfile)],
        ['query'],
      ),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
    'getBlacklist' : IDL.Func([], [IDL.Vec(BlacklistEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrawlQueue' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getDiscoverFeed' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [DiscoverFeed],
        ['query'],
      ),
    'getFlaggedDomains' : IDL.Func([], [IDL.Vec(BlacklistEntry)], ['query']),
    'getMyAdvertiserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdvertiserProfile)],
        ['query'],
      ),
    'getMyCampaigns' : IDL.Func([IDL.Text], [IDL.Vec(Campaign)], []),
    'getMyWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
    'getMyWebsitesByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Website)],
        ['query'],
      ),
    'getPagesForWebsite' : IDL.Func([IDL.Nat], [IDL.Vec(Page)], ['query']),
    'getPendingWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
    'getSecurityLogs' : IDL.Func([], [IDL.Vec(SecurityLog)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
    'getUserClickHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserInterests' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSearchHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getVerificationToken' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getWallet' : IDL.Func([IDL.Text], [IDL.Opt(AdvertiserWallet)], ['query']),
    'importSeedData' : IDL.Func([IDL.Vec(SeedEntry)], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAdSyncUser' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'pauseCampaign' : IDL.Func([IDL.Nat], [], []),
    'processPayouts' : IDL.Func([], [IDL.Vec(AdSyncPayoutLog)], []),
    'rankAds' : IDL.Func([IDL.Text], [IDL.Vec(AdMatchResult)], ['query']),
    'recalculateAllSpamScores' : IDL.Func([], [IDL.Nat], []),
    'recalculateSpamScore' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'reclaimDomain' : IDL.Func([IDL.Nat, IDL.Text], [Website], []),
    'recordAdClick' : IDL.Func([IDL.Nat, IDL.Text], [Result_6], []),
    'recordAdClickV2' : IDL.Func([IDL.Nat, IDL.Text], [Result_6], []),
    'recordAdImpression' : IDL.Func([IDL.Nat], [], []),
    'recordAdImpressionV2' : IDL.Func([IDL.Nat], [], []),
    'recordClick' : IDL.Func([IDL.Text], [], []),
    'recordImpression' : IDL.Func([IDL.Text], [], []),
    'recordUserClick' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordUserSearch' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'refreshUserInterests' : IDL.Func([IDL.Text], [], []),
    'registerAdSyncUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AdSyncAccountType,
          AdSyncRole,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Result_5],
        [],
      ),
    'rejectAdvertiser' : IDL.Func([IDL.Text], [], []),
    'rejectWebsite' : IDL.Func([IDL.Nat], [Website], []),
    'removeFromBlacklist' : IDL.Func([IDL.Text], [], []),
    'requestIndexing' : IDL.Func([IDL.Nat, IDL.Text], [Website], []),
    'resumeCampaign' : IDL.Func([IDL.Nat], [], []),
    'reviewFlaggedDomain' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'remove' : IDL.Null,
            'approve' : IDL.Null,
            'block' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'runCrawler' : IDL.Func([], [IDL.Nat], []),
    'runOwnershipCleanup' : IDL.Func([], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchWebsites' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(Website)],
        ['query'],
      ),
    'setAdSyncPaymentDetails' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          AdSyncPaymentMethod,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [Result_4],
        [],
      ),
    'setAdSyncRevenueShare' : IDL.Func([IDL.Nat], [Result_3], []),
    'setAdSyncTaxProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_3],
        [],
      ),
    'setAdminBoost' : IDL.Func([IDL.Nat, IDL.Nat], [Website], []),
    'setAdsEnabled' : IDL.Func([IDL.Bool], [], []),
    'submitAdSyncKyc' : IDL.Func([IDL.Text], [Result_2], []),
    'submitWebsite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Website],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCampaign' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [Campaign],
        [],
      ),
    'updateLastCrawledAt' : IDL.Func([IDL.Nat], [], []),
    'updatePageStatus' : IDL.Func([IDL.Nat, PageStatus], [], []),
    'updateSitemap' : IDL.Func([IDL.Nat, IDL.Text], [Website], []),
    'verifyAdSyncRazorpayPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_1],
        [],
      ),
    'verifyDomain' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'verifyRazorpayPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };